### ISSUE TITLE
Bugs and issues with donation certificate (from testing)

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#311] opened 2023-02-06 20:13 UTC
**Describe the bug** 
We started with sending out the certificates for the staff (real life testing). We observed following things: 

- [x] Failed payments are added to the total contribution amount
- [x] Apostrophe in French version (amount) can't be shown (see screenshot)
- [x] Street number is ignored in address field 
- [x] Email footer has some formatting issue (screenshot) #316
- [x] Preview text us not language specific and hard coded (screenshot) #316
- [x] #292 

FireCMS issues: 
- [ ] Changes made in admin tool (like address or language) is not picked up when re-generating a certificate (looks like some cache issue, as it works when being generated from another computer)
- [ ] Previous selection stays selected (dangerous)

**Screenshots**
<img width="486" alt="Screenshot 2023-02-06 at 20 53 28" src="https://user-images.githubusercontent.com/6095849/217071358-0e386488-30cd-4ad4-a6e3-9d7ae108e2de.png">
<img width="656" alt="Screenshot 2023-02-06 at 20 57 49" src="https://user-images.githubusercontent.com/6095849/217072234-b4b94bc3-0499-4f52-9571-1457de61571d.png">
<img width="613" alt="Screenshot 2023-02-06 at 20 59 17" src="https://user-images.githubusercontent.com/6095849/217072526-4d964b97-d27b-4592-90dc-28c74415d3ea.png">

**Additional context** 
Some bugs/features mentioned here might not be solved with this issue and moved to a separate issue.

**Comment by mkue** [comment] 2023-02-06 21:59
Thanks for the feedback. I'll have a look at the problems tomorrow👍 

> * Changes made in admin tool (like address or language) is not picked up when re-generating a certificate (looks like some cashing thing, as it works when being generated from another computer)
> * Previous selection stays selected (dangerous)

These are both FireCMS issues. The selection controller doesn't pick up the changes. Given the fact that we most likely won't create the certificates in the same way next year, I won't address this now.

**Comment by ssandino** [comment] 2023-02-07 15:38
> The selection controller doesn't pick up the changes.

Just saw in the [changelog](https://firecms.co/docs/changelog) that this one might be fixed by the latest version that was released a few days ago: _Fixed bug regarding custom selection controllers._

**Comment by mkue** [comment] 2023-02-07 22:21
I addressed most issues in #315. I merged the PR without any review, so I could test sending an email from Kerrin's email address. Works as expected :)

**Comment by mkue** [comment] 2023-02-07 22:25
The only thing that's now still broken in my eyes is the email formatting. @ssandino, are you sure that isn't happening with the other emails too? I have no experience with HTML emails, and the current template is a mess. Can you maybe copy/paste the email footer from an old template that's correct?

As soon as we switch to the mjml email template, this shouldn't be a problem anymore. The problem is that the mjml template is still pretty basic at the moment...

**Comment by ssandino** [comment] 2023-02-07 22:59
I fixed it in #316

**Closed** 2023-02-07 23:17 UTC
Labels: bug, admintool
